### ISSUE TITLE
How to make the window on top automatically when I open video every time

### ISSUE THREAD

**Issue by exxfzc** [SteveJobzniak/mpv-tools#1]
when i use mpv to open video,I just want to make the mpv window ontop automatically,not for using "T" every time!!!
Is there any way to do it?Thank you!

**Comment by SteveJobzniak** [comment]
I'm sorry, I just discovered that I wasn't "Watching" this repository so Github wasn't notifying me about new messages here!

Yes, you can make all windows automatically start in ontop mode by default. Just edit your `~/.config/mpv/mpv.conf` to add a line saying: `ontop=yes`.

This is what my own mpv.conf does:
```
# Disable all ugly window borders.
border=no

# Place the window in the middle of the screen.
geometry=50%:50%

# Set the maximum bounds of the player window upon initial opening. This
# shrinks the player window if the result would have been larger than the
# desktop resolution.
autofit-larger=90%x90%

# Make the player default to "always on top" mode.
ontop=yes
```
