### ISSUE TITLE
Backbox playlist manager: show title instead of file name 

### ISSUE THREAD

**Issue by lawmx** [SteveJobzniak/mpv-tools#3]
I'm using Backbox to manage a m3u playlist and I wonder if it may be possible to make it show the title from the m3u file instead of the file name.

**Comment by SteveJobzniak** [comment]
Hi! I wanna help if possible, so I am investigating right now. It looks like there may be a way to read the title, but I have to investigate. :-)

**Comment by SteveJobzniak** [comment]
Okay I've found the way to read the M3U title, but I need to carefully rewrite 28 code locations that deal with the filename, to be able to handle the title when available. I'll release an update as soon as possible. I'm working on it now...

**Comment by SteveJobzniak** [comment]
Alright @lawmx I've implemented the M3U title support.

And just for your info: I discovered that mpv isn't "sane" when dealing with M3U playlists. If you try the `[Clear Playlist]` command, or Backspace (to delete the last playlist item), or the "menu-left" command (to delete the selected item), mpv will actually retain the entire playlist but will forget all titles.

That's just some weird quirk of mpv itself. Seems like nobody on the team has ever tried deleting files from M3U playlists. You may want to make a ticket about that bug/whatever here:

https://github.com/mpv-player/mpv/issues

Anyway, Backbox now has support for M3U titles. Enjoy! :-) 🍰

**Comment by SteveJobzniak** [comment]
Nevermind what I just said about playlist clearing "troubles" in mpv. It actually works perfectly (that's a relief!). I just forgot that I had written a script which auto-queues files from the same folder, so my own script was re-adding them. ;-)

**Comment by lawmx** [comment]
Thanks a lot! I just sent you a little something as a token of appreciation :smile:

**Comment by SteveJobzniak** [comment]
@lawmx Wow, thanks a _lot_ to you as well! That was such an _awesome_ surprise here at the dawn of the new year. Open source donations are rare and you've really cheered me up at the perfect time! :-) I hope you have an awesome New Years Eve and that this new year is your best year yet! :-) // Johnny
